version: '3.1'

services:

  wordpress:
    image: wordpress:6.5.3-php8.1-apache
    restart: always
    container_name: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      JWT_AUTH_SECRET_KEY: 'DGm 98,x7fi>a/Z8C~Rk5ZM-TWQkA<h+,diPWN:]yn/a`j)]#[YN2pS U*WKYKoN'
    volumes:
      - ./html:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
